### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by victropolis** [ailyenko/Algorithms1#1]
Alex, I see that you're importing stuff from edu.princeton.cs.algs4, but will this work when submitting to the automated assessment on the coursera website?  I didn't know you could import from edu.princeton.cs.algs4, so what I did was install the algs4.jar and stdlib.jar in my local maven repository.

Have you submitted this and has it worked?  Just curious!

Thanks!

Victor

**Comment by ailyenko** [comment]
Hi Viktor,

No, submits with Maven imports won't work. You just need to import jars to your local project libs and use them.

As for me, I remove all maven repository imports and replace Java 8 logic with Java 7 one before submitting :)
