### ISSUE TITLE
About backwash in assignment 1, Percolation.java

### ISSUE THREAD

**Issue by neilsustc** [ailyenko/Algorithms1#2]
It seems that you didn't solve the "backwash" problem.
I run the PercolationVisualizer with input20.txt, it's the result
![backwash](https://cloud.githubusercontent.com/assets/7588612/9875671/9326fdbe-5be2-11e5-987a-b099d0c5d662.png)

But maybe the correct one should be
![nobackwash](https://cloud.githubusercontent.com/assets/7588612/9875689/c4e06b4c-5be2-11e5-9339-8e8ccfe69e5b.png)

**Comment by ailyenko** [comment]
It seems you're right. Do you have any ideas how can it be implemented in code?

**Comment by neilsustc** [comment]
I had looked for solutions for "backwash".
A straight-forward method is to declare another WeightedQuickUnionUF wquf2 which don't connect to the virtual bottom site. Use wquf(1) in function percolates(), use wquf2 in function isFull().
Someone provided another elegant approach but I can't understand...
This is the screenshot
![image](https://cloud.githubusercontent.com/assets/7588612/10020672/b8ca007c-6176-11e5-8ef4-0edd190766f3.png)

By the way, thank you for your codes. I'm learning Algorithms on Coursera recently. I often have a look at your codes after writing my own version. It's really helpful.

**Comment by ailyenko** [comment]
I guess I'll leave solution the way it is. Don't have enough time to change it.
You're welcome. Algorithms II will be here soon too :)

**Comment by neilsustc** [comment]
I think it's not important too. It's so trivial a problem.

**Comment by firezdog** [comment]
Implementing the solution provided does seem like it would be clever, but I think it's better to instantiate two UF's: the percolation client should not need to know details of how UF is implemented in order to determine whether a cell is full.  (Some implementations of UF might not have a findRoot method.)

**Comment by 6i96rother** [comment]
@yzhang-gh @firezdog @alexilyenko Hi guys! I thought you might be interested. I got another solution for backwash problem and all is needed is only single n*n+1 size array (I don't use OOTB union path structures). I use quick search + path compression algorithm. Though it's not as fast as weighted QU + path compression, it's logN, so it's fine. The main idea is to keep the greatest id as root and always set it as root on union operation. There's only 1 top abstract element. To check whether the grid percolates, we need to get top abstract element's root and check whether it's in the last row. Element with value -1 represents closed site. Please see the implementation [here:](https://github.com/6i96rother/Algorithms/blob/main/Percolation.java)

**Comment by OmarShawky1** [comment]
> @yzhang-gh @firezdog @alexilyenko Hi guys! I thought you might be interested. I got another solution for backwash problem and all is needed is only single n*n+1 size array (I don't use OOTB union path structures). I use quick search + path compression algorithm. Though it's not as fast as weighted QU + path compression, it's logN, so it's fine. The main idea is to keep the greatest id as root and always set it as root on union operation. There's only 1 top abstract element. To check whether the grid percolates, we need to get top abstract element's root and check whether it's in the last row. Element with value -1 represents closed site. Please see the implementation [here:](https://github.com/6i96rother/Algorithms/blob/main/Percolation.java)

This should not happen, he asked you to use Weighted Quick Union in specific. Also how did you pass the test? i see you use iterations `O(N)`, If you want a solution you can jump to my Algo repo but i do not think so because it has been a year now 😀️.
